export const DISTRICT_MAP: Array<any> = [
	{ id: 1, province_id: 1, name: 'Quận Ba Đình' },
	{ id: 2, province_id: 1, name: 'Quận Hoàn Kiếm' },
	{ id: 3, province_id: 1, name: 'Quận Tây Hồ' },
	{ id: 4, province_id: 1, name: 'Quận Long Biên' },
	{ id: 5, province_id: 1, name: 'Quận Cầu Giấy' },
	{ id: 6, province_id: 1, name: 'Quận Đống Đa' },
	{ id: 7, province_id: 1, name: 'Quận Hai Bà Trưng' },
	{ id: 8, province_id: 1, name: 'Quận Hoàng Mai' },
	{ id: 9, province_id: 1, name: 'Quận Thanh Xuân' },
	{ id: 10, province_id: 1, name: 'Huyện Sóc Sơn' },
	{ id: 11, province_id: 1, name: 'Huyện Đông Anh' },
	{ id: 12, province_id: 1, name: 'Huyện Gia Lâm' },
	{ id: 13, province_id: 1, name: 'Huyện Từ Liêm' },
	{ id: 14, province_id: 1, name: 'Huyện Thanh Trì' },
	{ id: 15, province_id: 1, name: 'Huyện Mê Linh' },
	{ id: 16, province_id: 1, name: 'Quận Hà Đông' },
	{ id: 17, province_id: 1, name: 'Thị Xã Sơn Tây' },
	{ id: 18, province_id: 1, name: 'Huyện Ba Vì' },
	{ id: 19, province_id: 1, name: 'Huyện Phúc Thọ' },
	{ id: 20, province_id: 1, name: 'Huyện Đan Phượng' },
	{ id: 21, province_id: 1, name: 'Huyện Hoài Đức' },
	{ id: 22, province_id: 1, name: 'Huyện Quốc Oai' },
	{ id: 23, province_id: 1, name: 'Huyện Thạch Thất' },
	{ id: 24, province_id: 1, name: 'Huyện Chương Mỹ' },
	{ id: 25, province_id: 1, name: 'Huyện Thanh Oai' },
	{ id: 26, province_id: 1, name: 'Huyện Thường Tín' },
	{ id: 27, province_id: 1, name: 'Huyện Phú Xuyên' },
	{ id: 28, province_id: 1, name: 'Huyện Ứng Hòa' },
	{ id: 29, province_id: 1, name: 'Huyện Mỹ Đức' },
	{ id: 30, province_id: 2, name: 'Thị Xã Hà Giang' },
	{ id: 31, province_id: 2, name: 'Huyện Đồng Văn' },
	{ id: 32, province_id: 2, name: 'Huyện Mèo Vạc' },
	{ id: 33, province_id: 2, name: 'Huyện Yên Minh' },
	{ id: 34, province_id: 2, name: 'Huyện Quản Bạ' },
	{ id: 35, province_id: 2, name: 'Huyện Vị Xuyên' },
	{ id: 36, province_id: 2, name: 'Huyện Bắc Mê' },
	{ id: 37, province_id: 2, name: 'Huyện Hoàng Su Phì' },
	{ id: 38, province_id: 2, name: 'Huyện Xín Mần' },
	{ id: 39, province_id: 2, name: 'Huyện Bắc Quang' },
	{ id: 40, province_id: 2, name: 'Huyện Quang Bình' },
	{ id: 41, province_id: 3, name: 'Thị Xã Cao Bằng' },
	{ id: 42, province_id: 3, name: 'Huyện Bảo Lâm' },
	{ id: 43, province_id: 3, name: 'Huyện Bảo Lạc' },
	{ id: 44, province_id: 3, name: 'Huyện Thông Nông' },
	{ id: 45, province_id: 3, name: 'Huyện Hà Quảng' },
	{ id: 46, province_id: 3, name: 'Huyện Trà Lĩnh' },
	{ id: 47, province_id: 3, name: 'Huyện Trùng Khánh' },
	{ id: 48, province_id: 3, name: 'Huyện Hạ Lang' },
	{ id: 49, province_id: 3, name: 'Huyện Quảng Uyên' },
	{ id: 50, province_id: 3, name: 'Huyện Phục Hoà' },
	{ id: 51, province_id: 3, name: 'Huyện Hoà An' },
	{ id: 52, province_id: 3, name: 'Huyện Nguyên Bình' },
	{ id: 53, province_id: 3, name: 'Huyện Thạch An' },
	{ id: 54, province_id: 4, name: 'Thị Xã Bắc Kạn' },
	{ id: 55, province_id: 4, name: 'Huyện Pác Nặm' },
	{ id: 56, province_id: 4, name: 'Huyện Ba Bể' },
	{ id: 57, province_id: 4, name: 'Huyện Ngân Sơn' },
	{ id: 58, province_id: 4, name: 'Huyện Bạch Thông' },
	{ id: 59, province_id: 4, name: 'Huyện Chợ Đồn' },
	{ id: 60, province_id: 4, name: 'Huyện Chợ Mới' },
	{ id: 61, province_id: 4, name: 'Huyện Na Rì' },
	{ id: 62, province_id: 5, name: 'Thị Xã Tuyên Quang' },
	{ id: 63, province_id: 5, name: 'Huyện Nà Hang' },
	{ id: 64, province_id: 5, name: 'Huyện Chiêm Hóa' },
	{ id: 65, province_id: 5, name: 'Huyện Hàm Yên' },
	{ id: 66, province_id: 5, name: 'Huyện Yên Sơn' },
	{ id: 67, province_id: 5, name: 'Huyện Sơn Dương' },
	{ id: 68, province_id: 6, name: 'Thành Phố Lào Cai' },
	{ id: 69, province_id: 6, name: 'Huyện Bát Xát' },
	{ id: 70, province_id: 6, name: 'Huyện Mường Khương' },
	{ id: 71, province_id: 6, name: 'Huyện Si Ma Cai' },
	{ id: 72, province_id: 6, name: 'Huyện Bắc Hà' },
	{ id: 73, province_id: 6, name: 'Huyện Bảo Thắng' },
	{ id: 74, province_id: 6, name: 'Huyện Bảo Yên' },
	{ id: 75, province_id: 6, name: 'Huyện Sa Pa' },
	{ id: 76, province_id: 6, name: 'Huyện Văn Bàn' },
	{ id: 77, province_id: 7, name: 'Thành Phố Điện Biên Phủ' },
	{ id: 78, province_id: 7, name: 'Thị Xã Mường Lay' },
	{ id: 79, province_id: 7, name: 'Huyện Mường Nhé' },
	{ id: 80, province_id: 7, name: 'Huyện Mường Chà' },
	{ id: 81, province_id: 7, name: 'Huyện Tủa Chùa' },
	{ id: 82, province_id: 7, name: 'Huyện Tuần Giáo' },
	{ id: 83, province_id: 7, name: 'Huyện Điện Biên' },
	{ id: 84, province_id: 7, name: 'Huyện Điện Biên Đông' },
	{ id: 85, province_id: 7, name: 'Huyện Mường Ảng' },
	{ id: 86, province_id: 8, name: 'Thị Xã Lai Châu' },
	{ id: 87, province_id: 8, name: 'Huyện Tam Đường' },
	{ id: 88, province_id: 8, name: 'Huyện Mường Tè' },
	{ id: 89, province_id: 8, name: 'Huyện Sìn Hồ' },
	{ id: 90, province_id: 8, name: 'Huyện Phong Thổ' },
	{ id: 91, province_id: 8, name: 'Huyện Than Uyên' },
	{ id: 92, province_id: 8, name: 'Huyện Tân Uyên' },
	{ id: 93, province_id: 9, name: 'Thành Phố Sơn La' },
	{ id: 94, province_id: 9, name: 'Huyện Quỳnh Nhai' },
	{ id: 95, province_id: 9, name: 'Huyện Thuận Châu' },
	{ id: 96, province_id: 9, name: 'Huyện Mường La' },
	{ id: 97, province_id: 9, name: 'Huyện Bắc Yên' },
	{ id: 98, province_id: 9, name: 'Huyện Phù Yên' },
	{ id: 99, province_id: 9, name: 'Huyện Mộc Châu' },
	{ id: 100, province_id: 9, name: 'Huyện Yên Châu' },
	{ id: 101, province_id: 9, name: 'Huyện Mai Sơn' },
	{ id: 102, province_id: 9, name: 'Huyện Sông Mã' },
	{ id: 103, province_id: 9, name: 'Huyện Sốp Cộp' },
	{ id: 104, province_id: 10, name: 'Thành Phố Yên Bái' },
	{ id: 105, province_id: 10, name: 'Thị Xã Nghĩa Lộ' },
	{ id: 106, province_id: 10, name: 'Huyện Lục Yên' },
	{ id: 107, province_id: 10, name: 'Huyện Văn Yên' },
	{ id: 108, province_id: 10, name: 'Huyện Mù Cang Chải' },
	{ id: 109, province_id: 10, name: 'Huyện Trấn Yên' },
	{ id: 110, province_id: 10, name: 'Huyện Trạm Tấu' },
	{ id: 111, province_id: 10, name: 'Huyện Văn Chấn' },
	{ id: 112, province_id: 10, name: 'Huyện Yên Bình' },
	{ id: 113, province_id: 11, name: 'Thành Phố Hòa Bình' },
	{ id: 114, province_id: 11, name: 'Huyện Đà Bắc' },
	{ id: 115, province_id: 11, name: 'Huyện Kỳ Sơn' },
	{ id: 116, province_id: 11, name: 'Huyện Lương Sơn' },
	{ id: 117, province_id: 11, name: 'Huyện Kim Bôi' },
	{ id: 118, province_id: 11, name: 'Huyện Cao Phong' },
	{ id: 119, province_id: 11, name: 'Huyện Tân Lạc' },
	{ id: 120, province_id: 11, name: 'Huyện Mai Châu' },
	{ id: 121, province_id: 11, name: 'Huyện Lạc Sơn' },
	{ id: 122, province_id: 11, name: 'Huyện Yên Thủy' },
	{ id: 123, province_id: 11, name: 'Huyện Lạc Thủy' },
	{ id: 124, province_id: 12, name: 'Thành Phố Thái Nguyên' },
	{ id: 125, province_id: 12, name: 'Thị Xã Sông Công' },
	{ id: 126, province_id: 12, name: 'Huyện Định Hóa' },
	{ id: 127, province_id: 12, name: 'Huyện Phú Lương' },
	{ id: 128, province_id: 12, name: 'Huyện Đồng Hỷ' },
	{ id: 129, province_id: 12, name: 'Huyện Võ Nhai' },
	{ id: 130, province_id: 12, name: 'Huyện Đại Từ' },
	{ id: 131, province_id: 12, name: 'Huyện Phổ Yên' },
	{ id: 132, province_id: 12, name: 'Huyện Phú Bình' },
	{ id: 133, province_id: 13, name: 'Thành Phố Lạng Sơn' },
	{ id: 134, province_id: 13, name: 'Huyện Tràng Định' },
	{ id: 135, province_id: 13, name: 'Huyện Bình Gia' },
	{ id: 136, province_id: 13, name: 'Huyện Văn Lãng' },
	{ id: 137, province_id: 13, name: 'Huyện Cao Lộc' },
	{ id: 138, province_id: 13, name: 'Huyện Văn Quan' },
	{ id: 139, province_id: 13, name: 'Huyện Bắc Sơn' },
	{ id: 140, province_id: 13, name: 'Huyện Hữu Lũng' },
	{ id: 141, province_id: 13, name: 'Huyện Chi Lăng' },
	{ id: 142, province_id: 13, name: 'Huyện Lộc Bình' },
	{ id: 143, province_id: 13, name: 'Huyện Đình Lập' },
	{ id: 144, province_id: 14, name: 'Thành Phố Hạ Long' },
	{ id: 145, province_id: 14, name: 'Thành Phố Móng Cái' },
	{ id: 146, province_id: 14, name: 'Thị Xã Cẩm Phả' },
	{ id: 147, province_id: 14, name: 'Thị Xã Uông Bí' },
	{ id: 148, province_id: 14, name: 'Huyện Bình Liêu' },
	{ id: 149, province_id: 14, name: 'Huyện Tiên Yên' },
	{ id: 150, province_id: 14, name: 'Huyện Đầm Hà' },
	{ id: 151, province_id: 14, name: 'Huyện Hải Hà' },
	{ id: 152, province_id: 14, name: 'Huyện Ba Chẽ' },
	{ id: 153, province_id: 14, name: 'Huyện Vân Đồn' },
	{ id: 154, province_id: 14, name: 'Huyện Hoành Bồ' },
	{ id: 155, province_id: 14, name: 'Huyện Đông Triều' },
	{ id: 156, province_id: 14, name: 'Huyện Yên Hưng' },
	{ id: 157, province_id: 14, name: 'Huyện Cô Tô' },
	{ id: 158, province_id: 15, name: 'Thành Phố Bắc Giang' },
	{ id: 159, province_id: 15, name: 'Huyện Yên Thế' },
	{ id: 160, province_id: 15, name: 'Huyện Tân Yên' },
	{ id: 161, province_id: 15, name: 'Huyện Lạng Giang' },
	{ id: 162, province_id: 15, name: 'Huyện Lục Nam' },
	{ id: 163, province_id: 15, name: 'Huyện Lục Ngạn' },
	{ id: 164, province_id: 15, name: 'Huyện Sơn Động' },
	{ id: 165, province_id: 15, name: 'Huyện Yên Dũng' },
	{ id: 166, province_id: 15, name: 'Huyện Việt Yên' },
	{ id: 167, province_id: 15, name: 'Huyện Hiệp Hòa' },
	{ id: 168, province_id: 16, name: 'Thành Phố Việt Trì' },
	{ id: 169, province_id: 16, name: 'Thị Xã Phú Thọ' },
	{ id: 170, province_id: 16, name: 'Huyện Đoan Hùng' },
	{ id: 171, province_id: 16, name: 'Huyện Hạ Hoà' },
	{ id: 172, province_id: 16, name: 'Huyện Thanh Ba' },
	{ id: 173, province_id: 16, name: 'Huyện Phù Ninh' },
	{ id: 174, province_id: 16, name: 'Huyện Yên Lập' },
	{ id: 175, province_id: 16, name: 'Huyện Cẩm Khê' },
	{ id: 176, province_id: 16, name: 'Huyện Tam Nông' },
	{ id: 177, province_id: 16, name: 'Huyện Lâm Thao' },
	{ id: 178, province_id: 16, name: 'Huyện Thanh Sơn' },
	{ id: 179, province_id: 16, name: 'Huyện Thanh Thuỷ' },
	{ id: 180, province_id: 16, name: 'Huyện Tân Sơn' },
	{ id: 181, province_id: 17, name: 'Thành Phố Vĩnh Yên' },
	{ id: 182, province_id: 17, name: 'Thị Xã Phúc Yên' },
	{ id: 183, province_id: 17, name: 'Huyện Lập Thạch' },
	{ id: 184, province_id: 17, name: 'Huyện Tam Dương' },
	{ id: 185, province_id: 17, name: 'Huyện Tam Đảo' },
	{ id: 186, province_id: 17, name: 'Huyện Bình Xuyên' },
	{ id: 187, province_id: 17, name: 'Huyện Yên Lạc' },
	{ id: 188, province_id: 17, name: 'Huyện Vĩnh Tường' },
	{ id: 189, province_id: 17, name: 'Huyện Sông Lô' },
	{ id: 190, province_id: 18, name: 'Thành Phố Bắc Ninh' },
	{ id: 191, province_id: 18, name: 'Huyện Yên Phong' },
	{ id: 192, province_id: 18, name: 'Huyện Quế Võ' },
	{ id: 193, province_id: 18, name: 'Huyện Tiên Du' },
	{ id: 194, province_id: 18, name: 'Thị Xã Từ Sơn' },
	{ id: 195, province_id: 18, name: 'Huyện Thuận Thành' },
	{ id: 196, province_id: 18, name: 'Huyện Gia Bình' },
	{ id: 197, province_id: 18, name: 'Huyện Lương Tài' },
	{ id: 198, province_id: 19, name: 'Thành Phố Hải Dương' },
	{ id: 199, province_id: 19, name: 'Huyện Chí Linh' },
	{ id: 200, province_id: 19, name: 'Huyện Nam Sách' },
	{ id: 201, province_id: 19, name: 'Huyện Kinh Môn' },
	{ id: 202, province_id: 19, name: 'Huyện Kim Thành' },
	{ id: 203, province_id: 19, name: 'Huyện Thanh Hà' },
	{ id: 204, province_id: 19, name: 'Huyện Cẩm Giàng' },
	{ id: 205, province_id: 19, name: 'Huyện Bình Giang' },
	{ id: 206, province_id: 19, name: 'Huyện Gia Lộc' },
	{ id: 207, province_id: 19, name: 'Huyện Tứ Kỳ' },
	{ id: 208, province_id: 19, name: 'Huyện Ninh Giang' },
	{ id: 209, province_id: 19, name: 'Huyện Thanh Miện' },
	{ id: 210, province_id: 20, name: 'Quận Hồng Bàng' },
	{ id: 211, province_id: 20, name: 'Quận Ngô Quyền' },
	{ id: 212, province_id: 20, name: 'Quận Lê Chân' },
	{ id: 213, province_id: 20, name: 'Quận Hải An' },
	{ id: 214, province_id: 20, name: 'Quận Kiến An' },
	{ id: 215, province_id: 20, name: 'Quận Đồ Sơn' },
	{ id: 216, province_id: 20, name: 'Quận Kinh Dương' },
	{ id: 217, province_id: 20, name: 'Huyện Thuỷ Nguyên' },
	{ id: 218, province_id: 20, name: 'Huyện An Dương' },
	{ id: 219, province_id: 20, name: 'Huyện An Lão' },
	{ id: 220, province_id: 20, name: 'Huyện Kiến Thụy' },
	{ id: 221, province_id: 20, name: 'Huyện Tiên Lãng' },
	{ id: 222, province_id: 20, name: 'Huyện Vĩnh Bảo' },
	{ id: 223, province_id: 20, name: 'Huyện Cát Hải' },
	{ id: 224, province_id: 20, name: 'Huyện Bạch Long Vĩ' },
	{ id: 225, province_id: 21, name: 'Thành Phố Hưng Yên' },
	{ id: 226, province_id: 21, name: 'Huyện Văn Lâm' },
	{ id: 227, province_id: 21, name: 'Huyện Văn Giang' },
	{ id: 228, province_id: 21, name: 'Huyện Yên Mỹ' },
	{ id: 229, province_id: 21, name: 'Huyện Mỹ Hào' },
	{ id: 230, province_id: 21, name: 'Huyện Ân Thi' },
	{ id: 231, province_id: 21, name: 'Huyện Khoái Châu' },
	{ id: 232, province_id: 21, name: 'Huyện Kim Động' },
	{ id: 233, province_id: 21, name: 'Huyện Tiên Lữ' },
	{ id: 234, province_id: 21, name: 'Huyện Phù Cừ' },
	{ id: 235, province_id: 22, name: 'Thành Phố Thái Bình' },
	{ id: 236, province_id: 22, name: 'Huyện Quỳnh Phụ' },
	{ id: 237, province_id: 22, name: 'Huyện Hưng Hà' },
	{ id: 238, province_id: 22, name: 'Huyện Đông Hưng' },
	{ id: 239, province_id: 22, name: 'Huyện Thái Thụy' },
	{ id: 240, province_id: 22, name: 'Huyện Tiền Hải' },
	{ id: 241, province_id: 22, name: 'Huyện Kiến Xương' },
	{ id: 242, province_id: 22, name: 'Huyện Vũ Thư' },
	{ id: 243, province_id: 23, name: 'Thành Phố Phủ Lý' },
	{ id: 244, province_id: 23, name: 'Huyện Duy Tiên' },
	{ id: 245, province_id: 23, name: 'Huyện Kim Bảng' },
	{ id: 246, province_id: 23, name: 'Huyện Thanh Liêm' },
	{ id: 247, province_id: 23, name: 'Huyện Bình Lục' },
	{ id: 248, province_id: 23, name: 'Huyện Lý Nhân' },
	{ id: 249, province_id: 24, name: 'Thành Phố Nam Định' },
	{ id: 250, province_id: 24, name: 'Huyện Mỹ Lộc' },
	{ id: 251, province_id: 24, name: 'Huyện Vụ Bản' },
	{ id: 252, province_id: 24, name: 'Huyện Ý Yên' },
	{ id: 253, province_id: 24, name: 'Huyện Nghĩa Hưng' },
	{ id: 254, province_id: 24, name: 'Huyện Nam Trực' },
	{ id: 255, province_id: 24, name: 'Huyện Trực Ninh' },
	{ id: 256, province_id: 24, name: 'Huyện Xuân Trường' },
	{ id: 257, province_id: 24, name: 'Huyện Giao Thủy' },
	{ id: 258, province_id: 24, name: 'Huyện Hải Hậu' },
	{ id: 259, province_id: 25, name: 'Thành Phố Ninh Bình' },
	{ id: 260, province_id: 25, name: 'Thị Xã Tam Điệp' },
	{ id: 261, province_id: 25, name: 'Huyện Nho Quan' },
	{ id: 262, province_id: 25, name: 'Huyện Gia Viễn' },
	{ id: 263, province_id: 25, name: 'Huyện Hoa Lư' },
	{ id: 264, province_id: 25, name: 'Huyện Yên Khánh' },
	{ id: 265, province_id: 25, name: 'Huyện Kim Sơn' },
	{ id: 266, province_id: 25, name: 'Huyện Yên Mô' },
	{ id: 267, province_id: 26, name: 'Thành Phố Thanh Hóa' },
	{ id: 268, province_id: 26, name: 'Thị Xã Bỉm Sơn' },
	{ id: 269, province_id: 26, name: 'Thị Xã Sầm Sơn' },
	{ id: 270, province_id: 26, name: 'Huyện Mường Lát' },
	{ id: 271, province_id: 26, name: 'Huyện Quan Hóa' },
	{ id: 272, province_id: 26, name: 'Huyện Bá Thước' },
	{ id: 273, province_id: 26, name: 'Huyện Quan Sơn' },
	{ id: 274, province_id: 26, name: 'Huyện Lang Chánh' },
	{ id: 275, province_id: 26, name: 'Huyện Ngọc Lặc' },
	{ id: 276, province_id: 26, name: 'Huyện Cẩm Thủy' },
	{ id: 277, province_id: 26, name: 'Huyện Thạch Thành' },
	{ id: 278, province_id: 26, name: 'Huyện Hà Trung' },
	{ id: 279, province_id: 26, name: 'Huyện Vĩnh Lộc' },
	{ id: 280, province_id: 26, name: 'Huyện Yên Định' },
	{ id: 281, province_id: 26, name: 'Huyện Thọ Xuân' },
	{ id: 282, province_id: 26, name: 'Huyện Thường Xuân' },
	{ id: 283, province_id: 26, name: 'Huyện Triệu Sơn' },
	{ id: 284, province_id: 26, name: 'Huyện Thiệu Hoá' },
	{ id: 285, province_id: 26, name: 'Huyện Hoằng Hóa' },
	{ id: 286, province_id: 26, name: 'Huyện Hậu Lộc' },
	{ id: 287, province_id: 26, name: 'Huyện Nga Sơn' },
	{ id: 288, province_id: 26, name: 'Huyện Như Xuân' },
	{ id: 289, province_id: 26, name: 'Huyện Như Thanh' },
	{ id: 290, province_id: 26, name: 'Huyện Nông Cống' },
	{ id: 291, province_id: 26, name: 'Huyện Đông Sơn' },
	{ id: 292, province_id: 26, name: 'Huyện Quảng Xương' },
	{ id: 293, province_id: 26, name: 'Huyện Tĩnh Gia' },
	{ id: 294, province_id: 27, name: 'Thành Phố Vinh' },
	{ id: 295, province_id: 27, name: 'Thị Xã Cửa Lò' },
	{ id: 296, province_id: 27, name: 'Thị Xã Thái Hoà' },
	{ id: 297, province_id: 27, name: 'Huyện Quế Phong' },
	{ id: 298, province_id: 27, name: 'Huyện Quỳ Châu' },
	{ id: 299, province_id: 27, name: 'Huyện Kỳ Sơn' },
	{ id: 300, province_id: 27, name: 'Huyện Tương Dương' },
	{ id: 301, province_id: 27, name: 'Huyện Nghĩa Đàn' },
	{ id: 302, province_id: 27, name: 'Huyện Quỳ Hợp' },
	{ id: 303, province_id: 27, name: 'Huyện Quỳnh Lưu' },
	{ id: 304, province_id: 27, name: 'Huyện Con Cuông' },
	{ id: 305, province_id: 27, name: 'Huyện Tân Kỳ' },
	{ id: 306, province_id: 27, name: 'Huyện Anh Sơn' },
	{ id: 307, province_id: 27, name: 'Huyện Diễn Châu' },
	{ id: 308, province_id: 27, name: 'Huyện Yên Thành' },
	{ id: 309, province_id: 27, name: 'Huyện Đô Lương' },
	{ id: 310, province_id: 27, name: 'Huyện Thanh Chương' },
	{ id: 311, province_id: 27, name: 'Huyện Nghi Lộc' },
	{ id: 312, province_id: 27, name: 'Huyện Nam Đàn' },
	{ id: 313, province_id: 27, name: 'Huyện Hưng Nguyên' },
	{ id: 314, province_id: 28, name: 'Thành Phố Hà Tĩnh' },
	{ id: 315, province_id: 28, name: 'Thị Xã Hồng Lĩnh' },
	{ id: 316, province_id: 28, name: 'Huyện Hương Sơn' },
	{ id: 317, province_id: 28, name: 'Huyện Đức Thọ' },
	{ id: 318, province_id: 28, name: 'Huyện Vũ Quang' },
	{ id: 319, province_id: 28, name: 'Huyện Nghi Xuân' },
	{ id: 320, province_id: 28, name: 'Huyện Can Lộc' },
	{ id: 321, province_id: 28, name: 'Huyện Hương Khê' },
	{ id: 322, province_id: 28, name: 'Huyện Thạch Hà' },
	{ id: 323, province_id: 28, name: 'Huyện Cẩm Xuyên' },
	{ id: 324, province_id: 28, name: 'Huyện Kỳ Anh' },
	{ id: 325, province_id: 28, name: 'Huyện Lộc Hà' },
	{ id: 326, province_id: 29, name: 'Thành Phố Đồng Hới' },
	{ id: 327, province_id: 29, name: 'Huyện Minh Hóa' },
	{ id: 328, province_id: 29, name: 'Huyện Tuyên Hóa' },
	{ id: 329, province_id: 29, name: 'Huyện Quảng Trạch' },
	{ id: 330, province_id: 29, name: 'Huyện Bố Trạch' },
	{ id: 331, province_id: 29, name: 'Huyện Quảng Ninh' },
	{ id: 332, province_id: 29, name: 'Huyện Lệ Thủy' },
	{ id: 333, province_id: 30, name: 'Thành Phố Đông Hà' },
	{ id: 334, province_id: 30, name: 'Thị Xã Quảng Trị' },
	{ id: 335, province_id: 30, name: 'Huyện Vĩnh Linh' },
	{ id: 336, province_id: 30, name: 'Huyện Hướng Hóa' },
	{ id: 337, province_id: 30, name: 'Huyện Gio Linh' },
	{ id: 338, province_id: 30, name: 'Huyện Đa Krông' },
	{ id: 339, province_id: 30, name: 'Huyện Cam Lộ' },
	{ id: 340, province_id: 30, name: 'Huyện Triệu Phong' },
	{ id: 341, province_id: 30, name: 'Huyện Hải Lăng' },
	{ id: 342, province_id: 30, name: 'Huyện Cồn Cỏ' },
	{ id: 343, province_id: 31, name: 'Thành Phố Huế' },
	{ id: 344, province_id: 31, name: 'Huyện Phong Điền' },
	{ id: 345, province_id: 31, name: 'Huyện Quảng Điền' },
	{ id: 346, province_id: 31, name: 'Huyện Phú Vang' },
	{ id: 347, province_id: 31, name: 'Huyện Hương Thủy' },
	{ id: 348, province_id: 31, name: 'Huyện Hương Trà' },
	{ id: 349, province_id: 31, name: 'Huyện A Lưới' },
	{ id: 350, province_id: 31, name: 'Huyện Phú Lộc' },
	{ id: 351, province_id: 31, name: 'Huyện Nam Đông' },
	{ id: 352, province_id: 32, name: 'Quận Liên Chiểu' },
	{ id: 353, province_id: 32, name: 'Quận Thanh Khê' },
	{ id: 354, province_id: 32, name: 'Quận Hải Châu' },
	{ id: 355, province_id: 32, name: 'Quận Sơn Trà' },
	{ id: 356, province_id: 32, name: 'Quận Ngũ Hành Sơn' },
	{ id: 357, province_id: 32, name: 'Quận Cẩm Lệ' },
	{ id: 358, province_id: 32, name: 'Huyện Hoà Vang' },
	{ id: 359, province_id: 32, name: 'Huyện Hoàng Sa' },
	{ id: 360, province_id: 33, name: 'Thành Phố Tam Kỳ' },
	{ id: 361, province_id: 33, name: 'Thành Phố Hội An' },
	{ id: 362, province_id: 33, name: 'Huyện Tây Giang' },
	{ id: 363, province_id: 33, name: 'Huyện Đông Giang' },
	{ id: 364, province_id: 33, name: 'Huyện Đại Lộc' },
	{ id: 365, province_id: 33, name: 'Huyện Điện Bàn' },
	{ id: 366, province_id: 33, name: 'Huyện Duy Xuyên' },
	{ id: 367, province_id: 33, name: 'Huyện Quế Sơn' },
	{ id: 368, province_id: 33, name: 'Huyện Nam Giang' },
	{ id: 369, province_id: 33, name: 'Huyện Phước Sơn' },
	{ id: 370, province_id: 33, name: 'Huyện Hiệp Đức' },
	{ id: 371, province_id: 33, name: 'Huyện Thăng Bình' },
	{ id: 372, province_id: 33, name: 'Huyện Tiên Phước' },
	{ id: 373, province_id: 33, name: 'Huyện Bắc Trà My' },
	{ id: 374, province_id: 33, name: 'Huyện Nam Trà My' },
	{ id: 375, province_id: 33, name: 'Huyện Núi Thành' },
	{ id: 376, province_id: 33, name: 'Huyện Phú Ninh' },
	{ id: 377, province_id: 33, name: 'Huyện Nông Sơn' },
	{ id: 378, province_id: 34, name: 'Thành Phố Quảng Ngãi' },
	{ id: 379, province_id: 34, name: 'Huyện Bình Sơn' },
	{ id: 380, province_id: 34, name: 'Huyện Trà Bồng' },
	{ id: 381, province_id: 34, name: 'Huyện Tây Trà' },
	{ id: 382, province_id: 34, name: 'Huyện Sơn Tịnh' },
	{ id: 383, province_id: 34, name: 'Huyện Tư Nghĩa' },
	{ id: 384, province_id: 34, name: 'Huyện Sơn Hà' },
	{ id: 385, province_id: 34, name: 'Huyện Sơn Tây' },
	{ id: 386, province_id: 34, name: 'Huyện Minh Long' },
	{ id: 387, province_id: 34, name: 'Huyện Nghĩa Hành' },
	{ id: 388, province_id: 34, name: 'Huyện Mộ Đức' },
	{ id: 389, province_id: 34, name: 'Huyện Đức Phổ' },
	{ id: 390, province_id: 34, name: 'Huyện Ba Tơ' },
	{ id: 391, province_id: 34, name: 'Huyện Lý Sơn' },
	{ id: 392, province_id: 35, name: 'Thành Phố Qui Nhơn' },
	{ id: 393, province_id: 35, name: 'Huyện An Lão' },
	{ id: 394, province_id: 35, name: 'Huyện Hoài Nhơn' },
	{ id: 395, province_id: 35, name: 'Huyện Hoài Ân' },
	{ id: 396, province_id: 35, name: 'Huyện Phù Mỹ' },
	{ id: 397, province_id: 35, name: 'Huyện Vĩnh Thạnh' },
	{ id: 398, province_id: 35, name: 'Huyện Tây Sơn' },
	{ id: 399, province_id: 35, name: 'Huyện Phù Cát' },
	{ id: 400, province_id: 35, name: 'Huyện An Nhơn' },
	{ id: 401, province_id: 35, name: 'Huyện Tuy Phước' },
	{ id: 402, province_id: 35, name: 'Huyện Vân Canh' },
	{ id: 403, province_id: 36, name: 'Thành Phố Tuy Hòa' },
	{ id: 404, province_id: 36, name: 'Thị Xã Sông Cầu' },
	{ id: 405, province_id: 36, name: 'Huyện Đồng Xuân' },
	{ id: 406, province_id: 36, name: 'Huyện Tuy An' },
	{ id: 407, province_id: 36, name: 'Huyện Sơn Hòa' },
	{ id: 408, province_id: 36, name: 'Huyện Sông Hinh' },
	{ id: 409, province_id: 36, name: 'Huyện Tây Hoà' },
	{ id: 410, province_id: 36, name: 'Huyện Phú Hoà' },
	{ id: 411, province_id: 36, name: 'Huyện Đông Hoà' },
	{ id: 412, province_id: 37, name: 'Thành Phố Nha Trang' },
	{ id: 413, province_id: 37, name: 'Thị Xã Cam Ranh' },
	{ id: 414, province_id: 37, name: 'Huyện Cam Lâm' },
	{ id: 415, province_id: 37, name: 'Huyện Vạn Ninh' },
	{ id: 416, province_id: 37, name: 'Huyện Ninh Hòa' },
	{ id: 417, province_id: 37, name: 'Huyện Khánh Vĩnh' },
	{ id: 418, province_id: 37, name: 'Huyện Diên Khánh' },
	{ id: 419, province_id: 37, name: 'Huyện Khánh Sơn' },
	{ id: 420, province_id: 37, name: 'Huyện Trường Sa' },
	{ id: 421, province_id: 38, name: 'Thành Phố Phan Rang-Tháp Chàm' },
	{ id: 422, province_id: 38, name: 'Huyện Bác Ái' },
	{ id: 423, province_id: 38, name: 'Huyện Ninh Sơn' },
	{ id: 424, province_id: 38, name: 'Huyện Ninh Hải' },
	{ id: 425, province_id: 38, name: 'Huyện Ninh Phước' },
	{ id: 426, province_id: 38, name: 'Huyện Thuận Bắc' },
	{ id: 427, province_id: 38, name: 'Huyện Thuận Nam' },
	{ id: 428, province_id: 39, name: 'Thành Phố Phan Thiết' },
	{ id: 429, province_id: 39, name: 'Thị Xã La Gi' },
	{ id: 430, province_id: 39, name: 'Huyện Tuy Phong' },
	{ id: 431, province_id: 39, name: 'Huyện Bắc Bình' },
	{ id: 432, province_id: 39, name: 'Huyện Hàm Thuận Bắc' },
	{ id: 433, province_id: 39, name: 'Huyện Hàm Thuận Nam' },
	{ id: 434, province_id: 39, name: 'Huyện Tánh Linh' },
	{ id: 435, province_id: 39, name: 'Huyện Đức Linh' },
	{ id: 436, province_id: 39, name: 'Huyện Hàm Tân' },
	{ id: 437, province_id: 39, name: 'Huyện Phú Quí' },
	{ id: 438, province_id: 40, name: 'Thành Phố Kon Tum' },
	{ id: 439, province_id: 40, name: 'Huyện Đắk Glei' },
	{ id: 440, province_id: 40, name: 'Huyện Ngọc Hồi' },
	{ id: 441, province_id: 40, name: 'Huyện Đắk Tô' },
	{ id: 442, province_id: 40, name: 'Huyện Kon Plông' },
	{ id: 443, province_id: 40, name: 'Huyện Kon Rẫy' },
	{ id: 444, province_id: 40, name: 'Huyện Đắk Hà' },
	{ id: 445, province_id: 40, name: 'Huyện Sa Thầy' },
	{ id: 446, province_id: 40, name: 'Huyện Tu Mơ Rông' },
	{ id: 447, province_id: 41, name: 'Thành Phố Pleiku' },
	{ id: 448, province_id: 41, name: 'Thị Xã An Khê' },
	{ id: 449, province_id: 41, name: 'Thị Xã Ayun Pa' },
	{ id: 450, province_id: 41, name: 'Huyện Kbang' },
	{ id: 451, province_id: 41, name: 'Huyện Đăk Đoa' },
	{ id: 452, province_id: 41, name: 'Huyện Chư Păh' },
	{ id: 453, province_id: 41, name: 'Huyện Ia Grai' },
	{ id: 454, province_id: 41, name: 'Huyện Mang Yang' },
	{ id: 455, province_id: 41, name: 'Huyện Kông Chro' },
	{ id: 456, province_id: 41, name: 'Huyện Đức Cơ' },
	{ id: 457, province_id: 41, name: 'Huyện Chư Prông' },
	{ id: 458, province_id: 41, name: 'Huyện Chư Sê' },
	{ id: 459, province_id: 41, name: 'Huyện Đăk Pơ' },
	{ id: 460, province_id: 41, name: 'Huyện Ia Pa' },
	{ id: 461, province_id: 41, name: 'Huyện Krông Pa' },
	{ id: 462, province_id: 41, name: 'Huyện Phú Thiện' },
	{ id: 463, province_id: 41, name: 'Huyện Chư Pưh' },
	{ id: 464, province_id: 42, name: 'Thành Phố Buôn Ma Thuột' },
	{ id: 465, province_id: 42, name: 'Thị Xã Buôn Hồ' },
	{ id: 466, province_id: 42, name: 'Huyện Ea H\'leo' },
	{ id: 467, province_id: 42, name: 'Huyện Ea Súp' },
	{ id: 468, province_id: 42, name: 'Huyện Buôn Đôn' },
	{ id: 469, province_id: 42, name: 'Huyện Cư M\'gar' },
	{ id: 470, province_id: 42, name: 'Huyện Krông Búk' },
	{ id: 471, province_id: 42, name: 'Huyện Krông Năng' },
	{ id: 472, province_id: 42, name: 'Huyện Ea Kar' },
	{ id: 473, province_id: 42, name: 'Huyện M\'đrắk' },
	{ id: 474, province_id: 42, name: 'Huyện Krông Bông' },
	{ id: 475, province_id: 42, name: 'Huyện Krông Pắc' },
	{ id: 476, province_id: 42, name: 'Huyện Krông A Na' },
	{ id: 477, province_id: 42, name: 'Huyện Lắk' },
	{ id: 478, province_id: 42, name: 'Huyện Cư Kuin' },
	{ id: 479, province_id: 43, name: 'Thị Xã Gia Nghĩa' },
	{ id: 480, province_id: 43, name: 'Huyện Đắk Glong' },
	{ id: 481, province_id: 43, name: 'Huyện Cư Jút' },
	{ id: 482, province_id: 43, name: 'Huyện Đắk Mil' },
	{ id: 483, province_id: 43, name: 'Huyện Krông Nô' },
	{ id: 484, province_id: 43, name: 'Huyện Đắk Song' },
	{ id: 485, province_id: 43, name: 'Huyện Đắk R\'lấp' },
	{ id: 486, province_id: 43, name: 'Huyện Tuy Đức' },
	{ id: 487, province_id: 44, name: 'Thành Phố Đà Lạt' },
	{ id: 488, province_id: 44, name: 'Thị Xã Bảo Lộc' },
	{ id: 489, province_id: 44, name: 'Huyện Đam Rông' },
	{ id: 490, province_id: 44, name: 'Huyện Lạc Dương' },
	{ id: 491, province_id: 44, name: 'Huyện Lâm Hà' },
	{ id: 492, province_id: 44, name: 'Huyện Đơn Dương' },
	{ id: 493, province_id: 44, name: 'Huyện Đức Trọng' },
	{ id: 494, province_id: 44, name: 'Huyện Di Linh' },
	{ id: 495, province_id: 44, name: 'Huyện Bảo Lâm' },
	{ id: 496, province_id: 44, name: 'Huyện Đạ Huoai' },
	{ id: 497, province_id: 44, name: 'Huyện Đạ Tẻh' },
	{ id: 498, province_id: 44, name: 'Huyện Cát Tiên' },
	{ id: 499, province_id: 45, name: 'Thị Xã Phước Long' },
	{ id: 500, province_id: 45, name: 'Thị Xã Đồng Xoài' },
	{ id: 501, province_id: 45, name: 'Thị Xã Bình Long' },
	{ id: 502, province_id: 45, name: 'Huyện Bù Gia Mập' },
	{ id: 503, province_id: 45, name: 'Huyện Lộc Ninh' },
	{ id: 504, province_id: 45, name: 'Huyện Bù Đốp' },
	{ id: 505, province_id: 45, name: 'Huyện Hớn Quản' },
	{ id: 506, province_id: 45, name: 'Huyện Đồng Phù' },
	{ id: 507, province_id: 45, name: 'Huyện Bù Đăng' },
	{ id: 508, province_id: 45, name: 'Huyện Chơn Thành' },
	{ id: 509, province_id: 46, name: 'Thị Xã Tây Ninh' },
	{ id: 510, province_id: 46, name: 'Huyện Tân Biên' },
	{ id: 511, province_id: 46, name: 'Huyện Tân Châu' },
	{ id: 512, province_id: 46, name: 'Huyện Dương Minh Châu' },
	{ id: 513, province_id: 46, name: 'Huyện Châu Thành' },
	{ id: 514, province_id: 46, name: 'Huyện Hòa Thành' },
	{ id: 515, province_id: 46, name: 'Huyện Gò Dầu' },
	{ id: 516, province_id: 46, name: 'Huyện Bến Cầu' },
	{ id: 517, province_id: 46, name: 'Huyện Trảng Bàng' },
	{ id: 518, province_id: 47, name: 'Thị Xã Thủ Dầu Một' },
	{ id: 519, province_id: 47, name: 'Huyện Dầu Tiếng' },
	{ id: 520, province_id: 47, name: 'Huyện Bến Cát' },
	{ id: 521, province_id: 47, name: 'Huyện Phú Giáo' },
	{ id: 522, province_id: 47, name: 'Huyện Tân Uyên' },
	{ id: 523, province_id: 47, name: 'Huyện Dĩ An' },
	{ id: 524, province_id: 47, name: 'Huyện Thuận An' },
	{ id: 525, province_id: 48, name: 'Thành Phố Biên Hòa' },
	{ id: 526, province_id: 48, name: 'Thị Xã Long Khánh' },
	{ id: 527, province_id: 48, name: 'Huyện Tân Phú' },
	{ id: 528, province_id: 48, name: 'Huyện Vĩnh Cửu' },
	{ id: 529, province_id: 48, name: 'Huyện Định Quán' },
	{ id: 530, province_id: 48, name: 'Huyện Trảng Bom' },
	{ id: 531, province_id: 48, name: 'Huyện Thống Nhất' },
	{ id: 532, province_id: 48, name: 'Huyện Cẩm Mỹ' },
	{ id: 533, province_id: 48, name: 'Huyện Long Thành' },
	{ id: 534, province_id: 48, name: 'Huyện Xuân Lộc' },
	{ id: 535, province_id: 48, name: 'Huyện Nhơn Trạch' },
	{ id: 536, province_id: 49, name: 'Thành Phố Vũng Tầu' },
	{ id: 537, province_id: 49, name: 'Thị Xã Bà Rịa' },
	{ id: 538, province_id: 49, name: 'Huyện Châu Đức' },
	{ id: 539, province_id: 49, name: 'Huyện Xuyên Mộc' },
	{ id: 540, province_id: 49, name: 'Huyện Long Điền' },
	{ id: 541, province_id: 49, name: 'Huyện Đất Đỏ' },
	{ id: 542, province_id: 49, name: 'Huyện Tân Thành' },
	{ id: 543, province_id: 49, name: 'Huyện Côn Đảo' },
	{ id: 544, province_id: 50, name: 'Quận 1' },
	{ id: 545, province_id: 50, name: 'Quận 12' },
	{ id: 546, province_id: 50, name: 'Quận Thủ Đức' },
	{ id: 547, province_id: 50, name: 'Quận 9' },
	{ id: 548, province_id: 50, name: 'Quận Gò Vấp' },
	{ id: 549, province_id: 50, name: 'Quận Bình Thạnh' },
	{ id: 550, province_id: 50, name: 'Quận Tân Bình' },
	{ id: 551, province_id: 50, name: 'Quận Tân Phú' },
	{ id: 552, province_id: 50, name: 'Quận Phú Nhuận' },
	{ id: 553, province_id: 50, name: 'Quận 2' },
	{ id: 554, province_id: 50, name: 'Quận 3' },
	{ id: 555, province_id: 50, name: 'Quận 10' },
	{ id: 556, province_id: 50, name: 'Quận 11' },
	{ id: 557, province_id: 50, name: 'Quận 4' },
	{ id: 558, province_id: 50, name: 'Quận 5' },
	{ id: 559, province_id: 50, name: 'Quận 6' },
	{ id: 560, province_id: 50, name: 'Quận 8' },
	{ id: 561, province_id: 50, name: 'Quận Bình Tân' },
	{ id: 562, province_id: 50, name: 'Quận 7' },
	{ id: 563, province_id: 50, name: 'Huyện Củ Chi' },
	{ id: 564, province_id: 50, name: 'Huyện Hóc Môn' },
	{ id: 565, province_id: 50, name: 'Huyện Bình Chánh' },
	{ id: 566, province_id: 50, name: 'Huyện Nhà Bè' },
	{ id: 567, province_id: 50, name: 'Huyện Cần Giờ' },
	{ id: 568, province_id: 51, name: 'Thành Phố Tân An' },
	{ id: 569, province_id: 51, name: 'Huyện Tân Hưng' },
	{ id: 570, province_id: 51, name: 'Huyện Vĩnh Hưng' },
	{ id: 571, province_id: 51, name: 'Huyện Mộc Hóa' },
	{ id: 572, province_id: 51, name: 'Huyện Tân Thạnh' },
	{ id: 573, province_id: 51, name: 'Huyện Thạnh Hóa' },
	{ id: 574, province_id: 51, name: 'Huyện Đức Huệ' },
	{ id: 575, province_id: 51, name: 'Huyện Đức Hòa' },
	{ id: 576, province_id: 51, name: 'Huyện Bến Lức' },
	{ id: 577, province_id: 51, name: 'Huyện Thủ Thừa' },
	{ id: 578, province_id: 51, name: 'Huyện Tân Trụ' },
	{ id: 579, province_id: 51, name: 'Huyện Cần Đước' },
	{ id: 580, province_id: 51, name: 'Huyện Cần Giuộc' },
	{ id: 581, province_id: 51, name: 'Huyện Châu Thành' },
	{ id: 582, province_id: 52, name: 'Thành Phố Mỹ Tho' },
	{ id: 583, province_id: 52, name: 'Thị Xã Gò Công' },
	{ id: 584, province_id: 52, name: 'Huyện Tân Phước' },
	{ id: 585, province_id: 52, name: 'Huyện Cái Bè' },
	{ id: 586, province_id: 52, name: 'Huyện Cai Lậy' },
	{ id: 587, province_id: 52, name: 'Huyện Châu Thành' },
	{ id: 588, province_id: 52, name: 'Huyện Chợ Gạo' },
	{ id: 589, province_id: 52, name: 'Huyện Gò Công Tây' },
	{ id: 590, province_id: 52, name: 'Huyện Gò Công Đông' },
	{ id: 591, province_id: 52, name: 'Huyện Tân Phú Đông' },
	{ id: 592, province_id: 53, name: 'Thành Phố Bến Tre' },
	{ id: 593, province_id: 53, name: 'Huyện Châu Thành' },
	{ id: 594, province_id: 53, name: 'Huyện Chợ Lách' },
	{ id: 595, province_id: 53, name: 'Huyện Mỏ Cày Nam' },
	{ id: 596, province_id: 53, name: 'Huyện Giồng Trôm' },
	{ id: 597, province_id: 53, name: 'Huyện Bình Đại' },
	{ id: 598, province_id: 53, name: 'Huyện Ba Tri' },
	{ id: 599, province_id: 53, name: 'Huyện Thạnh Phú' },
	{ id: 600, province_id: 53, name: 'Huyện Mỏ Cày Bắc' },
	{ id: 601, province_id: 54, name: 'Thị Xã Trà Vinh' },
	{ id: 602, province_id: 54, name: 'Huyện Càng Long' },
	{ id: 603, province_id: 54, name: 'Huyện Cầu Kè' },
	{ id: 604, province_id: 54, name: 'Huyện Tiểu Cần' },
	{ id: 605, province_id: 54, name: 'Huyện Châu Thành' },
	{ id: 606, province_id: 54, name: 'Huyện Cầu Ngang' },
	{ id: 607, province_id: 54, name: 'Huyện Trà Cú' },
	{ id: 608, province_id: 54, name: 'Huyện Duyên Hải' },
	{ id: 609, province_id: 55, name: 'Thành Phố Vĩnh Long' },
	{ id: 610, province_id: 55, name: 'Huyện Long Hồ' },
	{ id: 611, province_id: 55, name: 'Huyện Mang Thít' },
	{ id: 612, province_id: 55, name: 'Huyện Vũng Liêm' },
	{ id: 613, province_id: 55, name: 'Huyện Tam Bình' },
	{ id: 614, province_id: 55, name: 'Huyện Bình Minh' },
	{ id: 615, province_id: 55, name: 'Huyện Trà Ôn' },
	{ id: 616, province_id: 55, name: 'Huyện Bình Tân' },
	{ id: 617, province_id: 56, name: 'Thành Phố Cao Lãnh' },
	{ id: 618, province_id: 56, name: 'Thị Xã Sa Đéc' },
	{ id: 619, province_id: 56, name: 'Thị Xã Hồng Ngự' },
	{ id: 620, province_id: 56, name: 'Huyện Tân Hồng' },
	{ id: 621, province_id: 56, name: 'Huyện Hồng Ngự' },
	{ id: 622, province_id: 56, name: 'Huyện Tam Nông' },
	{ id: 623, province_id: 56, name: 'Huyện Tháp Mười' },
	{ id: 624, province_id: 56, name: 'Huyện Cao Lãnh' },
	{ id: 625, province_id: 56, name: 'Huyện Thanh Bình' },
	{ id: 626, province_id: 56, name: 'Huyện Lấp Vò' },
	{ id: 627, province_id: 56, name: 'Huyện Lai Vung' },
	{ id: 628, province_id: 56, name: 'Huyện Châu Thành' },
	{ id: 629, province_id: 57, name: 'Thành Phố Long Xuyên' },
	{ id: 630, province_id: 57, name: 'Thị Xã Châu Đốc' },
	{ id: 631, province_id: 57, name: 'Huyện An Phú' },
	{ id: 632, province_id: 57, name: 'Thị Xã Tân Châu' },
	{ id: 633, province_id: 57, name: 'Huyện Phú Tân' },
	{ id: 634, province_id: 57, name: 'Huyện Châu Phú' },
	{ id: 635, province_id: 57, name: 'Huyện Tịnh Biên' },
	{ id: 636, province_id: 57, name: 'Huyện Tri Tôn' },
	{ id: 637, province_id: 57, name: 'Huyện Châu Thành' },
	{ id: 638, province_id: 57, name: 'Huyện Chợ Mới' },
	{ id: 639, province_id: 57, name: 'Huyện Thoại Sơn' },
	{ id: 640, province_id: 58, name: 'Thành Phố Rạch Giá' },
	{ id: 641, province_id: 58, name: 'Thị Xã Hà Tiên' },
	{ id: 642, province_id: 58, name: 'Huyện Kiên Lương' },
	{ id: 643, province_id: 58, name: 'Huyện Hòn Đất' },
	{ id: 644, province_id: 58, name: 'Huyện Tân Hiệp' },
	{ id: 645, province_id: 58, name: 'Huyện Châu Thành' },
	{ id: 646, province_id: 58, name: 'Huyện Giồng Giềng' },
	{ id: 647, province_id: 58, name: 'Huyện Gò Quao' },
	{ id: 648, province_id: 58, name: 'Huyện An Biên' },
	{ id: 649, province_id: 58, name: 'Huyện An Minh' },
	{ id: 650, province_id: 58, name: 'Huyện Vĩnh Thuận' },
	{ id: 651, province_id: 58, name: 'Huyện Phú Quốc' },
	{ id: 652, province_id: 58, name: 'Huyện Kiên Hải' },
	{ id: 653, province_id: 58, name: 'Huyện U Minh Thượng' },
	{ id: 654, province_id: 58, name: 'Huyện Giang Thành' },
	{ id: 655, province_id: 59, name: 'Quận Ninh Kiều' },
	{ id: 656, province_id: 59, name: 'Quận Ô Môn' },
	{ id: 657, province_id: 59, name: 'Quận Bình Thuỷ' },
	{ id: 658, province_id: 59, name: 'Quận Cái Răng' },
	{ id: 659, province_id: 59, name: 'Quận Thốt Nốt' },
	{ id: 660, province_id: 59, name: 'Huyện Vĩnh Thạnh' },
	{ id: 661, province_id: 59, name: 'Huyện Cờ Đỏ' },
	{ id: 662, province_id: 59, name: 'Huyện Phong Điền' },
	{ id: 663, province_id: 59, name: 'Huyện Thới Lai' },
	{ id: 664, province_id: 60, name: 'Thị Xã Vị Thanh' },
	{ id: 665, province_id: 60, name: 'Thị Xã Ngã Bảy' },
	{ id: 666, province_id: 60, name: 'Huyện Châu Thành A' },
	{ id: 667, province_id: 60, name: 'Huyện Châu Thành' },
	{ id: 668, province_id: 60, name: 'Huyện Phụng Hiệp' },
	{ id: 669, province_id: 60, name: 'Huyện Vị Thuỷ' },
	{ id: 670, province_id: 60, name: 'Huyện Long Mỹ' },
	{ id: 671, province_id: 61, name: 'Thành Phố Sóc Trăng' },
	{ id: 672, province_id: 61, name: 'Huyện Châu Thành' },
	{ id: 673, province_id: 61, name: 'Huyện Kế Sách' },
	{ id: 674, province_id: 61, name: 'Huyện Mỹ Tú' },
	{ id: 675, province_id: 61, name: 'Huyện Cù Lao Dung' },
	{ id: 676, province_id: 61, name: 'Huyện Long Phú' },
	{ id: 677, province_id: 61, name: 'Huyện Mỹ Xuyên' },
	{ id: 678, province_id: 61, name: 'Huyện Ngã Năm' },
	{ id: 679, province_id: 61, name: 'Huyện Thạnh Trị' },
	{ id: 680, province_id: 61, name: 'Huyện Vĩnh Châu' },
	{ id: 681, province_id: 61, name: 'Huyện Trần Đề' },
	{ id: 682, province_id: 62, name: 'Thị Xã Bạc Liêu' },
	{ id: 683, province_id: 62, name: 'Huyện Hồng Dân' },
	{ id: 684, province_id: 62, name: 'Huyện Phước Long' },
	{ id: 685, province_id: 62, name: 'Huyện Vĩnh Lợi' },
	{ id: 686, province_id: 62, name: 'Huyện Giá Rai' },
	{ id: 687, province_id: 62, name: 'Huyện Đông Hải' },
	{ id: 688, province_id: 62, name: 'Huyện Hoà Bình' },
	{ id: 689, province_id: 63, name: 'Thành Phố Cà Mau' },
	{ id: 690, province_id: 63, name: 'Huyện U Minh' },
	{ id: 691, province_id: 63, name: 'Huyện Thới Bình' },
	{ id: 692, province_id: 63, name: 'Huyện Trần Văn Thời' },
	{ id: 693, province_id: 63, name: 'Huyện Cái Nước' },
	{ id: 694, province_id: 63, name: 'Huyện Đầm Dơi' },
	{ id: 695, province_id: 63, name: 'Huyện Năm Căn' },
	{ id: 696, province_id: 63, name: 'Huyện Phú Tân' },
	{ id: 697, province_id: 63, name: 'Huyện Ngọc Hiển' },
];
