export const PROVINCE_MAP: Array<any> = [
	{ id: 1, country_id: 1, name: 'Thành Phố Hà Nội' },
	{ id: 2, country_id: 1, name: 'Tỉnh Hà Giang' },
	{ id: 3, country_id: 1, name: 'Tỉnh Cao Bằng' },
	{ id: 4, country_id: 1, name: 'Tỉnh Bắc Kạn' },
	{ id: 5, country_id: 1, name: 'Tỉnh Tuyên Quang' },
	{ id: 6, country_id: 1, name: 'Tỉnh Lào Cai' },
	{ id: 7, country_id: 1, name: 'Tỉnh Điện Biên' },
	{ id: 8, country_id: 1, name: 'Tỉnh Lai Châu' },
	{ id: 9, country_id: 1, name: 'Tỉnh Sơn La' },
	{ id: 10, country_id: 1, name: 'Tỉnh Yên Bái' },
	{ id: 11, country_id: 1, name: 'Tỉnh Hòa Bình' },
	{ id: 12, country_id: 1, name: 'Tỉnh Thái Nguyên' },
	{ id: 13, country_id: 1, name: 'Tỉnh Lạng Sơn' },
	{ id: 14, country_id: 1, name: 'Tỉnh Quảng Ninh' },
	{ id: 15, country_id: 1, name: 'Tỉnh Bắc Giang' },
	{ id: 16, country_id: 1, name: 'Tỉnh Phú Thọ' },
	{ id: 17, country_id: 1, name: 'Tỉnh Vĩnh Phúc' },
	{ id: 18, country_id: 1, name: 'Tỉnh Bắc Ninh' },
	{ id: 19, country_id: 1, name: 'Tỉnh Hải Dương' },
	{ id: 20, country_id: 1, name: 'Thành Phố Hải Phòng' },
	{ id: 21, country_id: 1, name: 'Tỉnh Hưng Yên' },
	{ id: 22, country_id: 1, name: 'Tỉnh Thái Bình' },
	{ id: 23, country_id: 1, name: 'Tỉnh Hà Nam' },
	{ id: 24, country_id: 1, name: 'Tỉnh Nam Định' },
	{ id: 25, country_id: 1, name: 'Tỉnh Ninh Bình' },
	{ id: 26, country_id: 1, name: 'Tỉnh Thanh Hóa' },
	{ id: 27, country_id: 1, name: 'Tỉnh Nghệ An' },
	{ id: 28, country_id: 1, name: 'Tỉnh Hà Tĩnh' },
	{ id: 29, country_id: 1, name: 'Tỉnh Quảng Bình' },
	{ id: 30, country_id: 1, name: 'Tỉnh Quảng Trị' },
	{ id: 31, country_id: 1, name: 'Tỉnh Thừa Thiên Huế' },
	{ id: 32, country_id: 1, name: 'Thành Phố Đà Nẵng' },
	{ id: 33, country_id: 1, name: 'Tỉnh Quảng Nam' },
	{ id: 34, country_id: 1, name: 'Tỉnh Quảng Ngãi' },
	{ id: 35, country_id: 1, name: 'Tỉnh Bình Định' },
	{ id: 36, country_id: 1, name: 'Tỉnh Phú Yên' },
	{ id: 37, country_id: 1, name: 'Tỉnh Khánh Hòa' },
	{ id: 38, country_id: 1, name: 'Tỉnh Ninh Thuận' },
	{ id: 39, country_id: 1, name: 'Tỉnh Bình Thuận' },
	{ id: 40, country_id: 1, name: 'Tỉnh Kon Tum' },
	{ id: 41, country_id: 1, name: 'Tỉnh Gia Lai' },
	{ id: 42, country_id: 1, name: 'Tỉnh Đắk Lắk' },
	{ id: 43, country_id: 1, name: 'Tỉnh Đắk Nông' },
	{ id: 44, country_id: 1, name: 'Tỉnh Lâm Đồng' },
	{ id: 45, country_id: 1, name: 'Tỉnh Bình Phước' },
	{ id: 46, country_id: 1, name: 'Tỉnh Tây Ninh' },
	{ id: 47, country_id: 1, name: 'Tỉnh Bình Dương' },
	{ id: 48, country_id: 1, name: 'Tỉnh Đồng Nai' },
	{ id: 49, country_id: 1, name: 'Tỉnh Bà Rịa - Vũng Tàu' },
	{ id: 50, country_id: 1, name: 'Thành Phố Hồ Chí Minh' },
	{ id: 51, country_id: 1, name: 'Tỉnh Long An' },
	{ id: 52, country_id: 1, name: 'Tỉnh Tiền Giang' },
	{ id: 53, country_id: 1, name: 'Tỉnh Bến Tre' },
	{ id: 54, country_id: 1, name: 'Tỉnh Trà Vinh' },
	{ id: 55, country_id: 1, name: 'Tỉnh Vĩnh Long' },
	{ id: 56, country_id: 1, name: 'Tỉnh Đồng Tháp' },
	{ id: 57, country_id: 1, name: 'Tỉnh An Giang' },
	{ id: 58, country_id: 1, name: 'Tỉnh Kiên Giang' },
	{ id: 59, country_id: 1, name: 'Thành Phố Cần Thơ' },
	{ id: 60, country_id: 1, name: 'Tỉnh Hậu Giang' },
	{ id: 61, country_id: 1, name: 'Tỉnh Sóc Trăng' },
	{ id: 62, country_id: 1, name: 'Tỉnh Bạc Liêu' },
	{ id: 63, country_id: 1, name: 'Tỉnh Cà Mau' },
];
